CREATE TABLE IF NOT EXISTS analyses (

    id INTEGER PRIMARY KEY AUTOINCREMENT,

    data TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    tipo TEXT,

    score INTEGER,

    categoria TEXT,

    texto TEXT
);